### ISSUE TITLE
How to specify options for prettier-plugin-sql?

### ISSUE THREAD

**Issue by jgonera** [Sec-ant/prettier-plugin-embed#16]
First of all, thank you for creating this plugin! It's exactly what I've been looking for in a while.

I managed to make it work pretty easily, but I'd like to customize the options passed to `prettier-plugin-sql`. In the readme you say:

> And [options](https://github.com/un-ts/prettier/tree/master/packages/sql#parser-options) supported by prettier-plugin-sql can therefore be used to further control the formatting behavior.

But I am not sure where to put those options. My Prettier config looks like this now:

```js
export default {
  semi: false,
  singleQuote: true,
  trailingComma: 'none',
  plugins: ['prettier-plugin-embed', 'prettier-plugin-sql'],
  overrides: [
    {
      files: '*.sql',
      options: {
        formatter: 'sql-formatter',
        keywordCase: 'upper',
        language: 'mysql'
      }
    }
  ]
}
```

I would like to use the same options for SQL template literals as I'm using for `*.sql` files so MySQL as a language and uppercase keywords. How can I set this up?

**Comment by Sec-ant** [comment]
Oh shoot, I wasn't even considering about the `overrides` fields. I'll need to reevaluate the way to configure it.

This plugin only expects and uses options

**Comment by jgonera** [comment]
I see now, I think I misunderstood how Prettier plugin options work in general. I just changed my Prettier config to this and it works as expected:

```js
export default {
  semi: false,
  singleQuote: true,
  trailingComma: 'none',
  plugins: ['prettier-plugin-embed', 'prettier-plugin-sql'],
  // prettier-plugin-sql options
  formatter: 'sql-formatter',
  keywordCase: 'upper',
  language: 'mysql'
}
```

I wrongly assumed that the options for SQL have to be under `overrides`. I guess they can be global. That makes me wonder what happens if two Prettier plugins define an option with the same name but I suppose that's a problem with Prettier and not `prettier-plugin-embed` 😄 

Thank you again for this plugin, so far works like a charm!

**Comment by Sec-ant** [comment]
As this plugin is meant to be used to format embedded languages in *`.ts`* or *`.js`* files, any options specified in `overrides` for other file extensions like `*.sql` are unseenable from this plugin's point of view.

> That makes me wonder what happens if two Prettier plugins define an option with the same name

You're absolutely right. Options in Prettier is the source of headache as only simple values (number, string, number list, string list) are supported when implementing a plugin. I once had a vision where options in different languages were scoped in different objects under a big object before I jumped in developing this, but it soon became broken bubbles the moment I realized the restrictions.

**Comment by karlhorky** [comment]
@Sec-ant just as feedback here, it would be cool to see a few config examples like the config code examples above in the readme.

Either

A) full interactive examples (eg. CodeSandbox) or "recipes"
B) including configuration and code as in below

`prettier.config.js`

```js
/** @type {import('prettier').Config} */
const config = {
  plugins: ['prettier-plugin-embed', 'prettier-plugin-sql'],

  // prettier-plugin-sql options
  formatter: 'sql-formatter',
  keywordCase: 'upper',
  language: 'mysql',
};

export default config;
```

`index.ts` (before)

```js
const animals = await sql`
      SELECT
*                 
                       FROM
       animals
`;
```

`index.ts` (after)

```js
const animals = await sql`
  SELECT
    *                 
  FROM
    animals
`;
```

**Comment by Sec-ant** [comment]
@karlhorky thanks for the suggestion and the example, I totally agree with you.

I think we can do both. Though I haven't test whether this plugin works on those online platforms.

And feel free to create PRs for the README documentation if you want, just for only one language is also okay :).

**Comment by karlhorky** [comment]
Ok great, I added an issue for now to track it:

- https://github.com/Sec-ant/prettier-plugin-embed/issues/20

Not sure if I will get around to creating a PR for this any time soon.

**Comment by icopp** [comment]
Given the lack of overrides, is there any way to (for example) have the `tabWidth` of an embedded SQL block be 4 while the global `tabWidth` is 2?

**Comment by Sec-ant** [comment]
@icopp I don't think this is possible right now unless we support some hacky workarounds like adding another `embeddedOverrides` option and accepting a stringified JSON (we can't use objects in options) to customize the settings for embedded languages only.

**Comment by Sec-ant** [comment]
Some experiments on the thoughts https://github.com/Sec-ant/prettier-plugin-embed/issues/16#issuecomment-1783658897. It basically works.

**(THIS IS NOT IMPLEMENTED YET)**

![image](https://github.com/Sec-ant/prettier-plugin-embed/assets/10386119/c0743446-7f0a-4b30-8f0a-376d8cc90c9c)

If we can accept `JSON.stringify` or loading options from another file with an absolute path, we may redesign the whole API of this plugin in this way.

**Comment by karlhorky** [comment]
cc @sosukesuzuki @fisker @thorn0 in case you would have feedback here about the approach of `JSON.stringify()` to pass in the overrides for the embedded languages

**Comment by Sec-ant** [comment]
@karlhorky thanks for bending over backwards for this plugin ♥️
