### ISSUE TITLE
Support JS(X) & TS(X) blocks

### ISSUE THREAD

**Issue by MichaelDeBoey** [Sec-ant/prettier-plugin-embed#17]
See https://github.com/prettier/prettier/issues/15265 & https://github.com/prettier/prettier/issues/15266

**Comment by Sec-ant** [comment]
I think they're already supported, do you have any uses case where it fails?

![Animation3](https://github.com/Sec-ant/prettier-plugin-embed/assets/10386119/8a0f960a-a042-46a5-b99d-31bec0f4e4b7)

**Comment by MichaelDeBoey** [comment]
@Sec-ant I'm looking for a solution to use template literal tags, not comments like in your video

```ts
js`
  // ...
`
jsx`
  // ...
`
ts`
  // ...
`
tsx`
  // ...
`
```

**Comment by Sec-ant** [comment]
Sorry for my late response (my mind was occupied by another project).

I believe what you requested are already supported, too. Comments and tagged functions as identifiers are both activated by default:

![prettier-plugin-embed-](https://github.com/Sec-ant/prettier-plugin-embed/assets/10386119/e9287f52-4e22-48cb-9fc1-9c8aa35d266c)
