### ISSUE TITLE
Ability to map `sql` to `postgresql`

### ISSUE THREAD

**Issue by innermatrix** [Sec-ant/prettier-plugin-embed#26]
Thanks for your work! 

I could be missing something in the docs, but from what I understand, if I wanted `xyzzy` to mean `postgres`, I could set `embeddedSqlIdentifiers` to `['postgresql', 'xyzzy']`, but I am not sure how to make `sql` mean `postgresql` because `sql` is already its own dialect. 

I think that overriding `sql` to mean a specific dialect will be a very common use case so I hope this can be added as a feature. I think a simple implementation might be to allow something like `embeddedSqlIdentifiers = ['sql:postgresql', …].

**Comment by Sec-ant** [comment]
Thanks for the feedback, this is a good point. I'm not very satisfied with the current api either. But I'm not sure if I want to implement a new syntax only for sql tags or there're some other ways around.

**Comment by innermatrix** [comment]
Yeah, the set of decisions that lead us here is kinda funky. `prettier` decided that we can select the language on a per-file basis (using filename extensions), then `prettier-plugin-sql` decided that all SQL is one language but you can select which dialect to use for the entire project (in `.prettierrc`), and then `prettier-plugin-embed` decided that we can select both the language and the dialect for each string (using the template tag), but the unfortunate outcome is that we can't select what I imagine is the most common use of the `sql` template tag — selecting a vendor dialect (like PostgreSQL) for the non-vendor-specific `sql` tag. 

If you want to keep this simple and not reinvent the wheel, my best guess is that you should just let SQL dialects behave the same way in string literals as they do in SQL files, which is to say that you get choose a dialect globally and live with it. Everyone who's using `prettier-plugin-sql` is already stuck with a global choice of SQL dialect, so you wouldn't be making it worse.

**Comment by Sec-ant** [comment]
The dialect choice provided by `prettier-plugin-sql` is overridden automatically by this plugin while parsing the sql template strings, and I intend to keep it this way so users can format different dialects of sql template strings in the same js file.

I'm considering adding a new option `embeddedSqlDialectMapping` to let users remap the identifiers to different dialects explicitly while keeping the current mechanism as a fallback. This new option can use the syntax you suggested. Is this acceptable?

**Comment by innermatrix** [comment]
Totally. Once again tyvm!

**Comment by Sec-ant** [comment]
Hi @innermatrix 

I added a new option called [`embeddedOverrides`](https://github.com/Sec-ant/prettier-plugin-embed#embeddedoverrides) which should be able to solve this issue and others as well. I didn't add `embeddedSqlDialectMapping` because `embeddedOverrides` is already planned when you raise this issue and it is more versatile.

For your use case, you can consider this minimal option in your prettier config:

```json
{
  "plugins": ["prettier-plugin-embed", "prettier-plugin-sql"],
  "embeddedSqlIdentifiers": ["sql"],
  "embeddedOverrides": "[{\"identifiers\":[\"sql\"],\"options\":{\"formatter\":\"sql-formatter\",\"language\":\"postgresql\"}}]"
}
```

Unfortunately, due to the limitation of prettier https://github.com/prettier/prettier/issues/14671, we have to use a stringified json string in the `embeddedOverrides`, which is kind of ugly, but you can also use an **absolute** file path referring to a json file containing the overrides.

This feature is released in [`v0.3.0-rc.0`](https://github.com/Sec-ant/prettier-plugin-embed/releases/tag/v0.3.0-rc.0). Please check if this works when you have time.

**Comment by JounQin** [comment]
Or you can use js prettier config so that `JSON.stringify` can be used.

**Comment by Sec-ant** [comment]
> Or you can use js prettier config so that `JSON.stringify` can be used.

@JounQin yep, thanks for pointing that out, I just edited my comment.

**Comment by innermatrix** [comment]
@Sec-ant works tyvm

**Comment by Sec-ant** [comment]
Thanks for all the feedbacks, I'm now closing this.

Track #33 for the support of relative file path, as well as using `.cjs`, `.ejs`, `.js` (or even `.cts`, `.ets`, `.ts`) file paths for this option. I plan to include these enhancements in v0.3.0.

**Comment by Sec-ant** [comment]
v0.3.0 discards this auto mapping behavior. You can just use `language: ["postgresql"]` now. `embeddedOverrides` is no longer needed.
