### ISSUE TITLE
sql-formatter crash on SQL casts, tilde, square brackets, `$$` delimiter

### ISSUE THREAD

**Issue by karlhorky** [Sec-ant/prettier-plugin-embed#35]
Hi @Sec-ant , hope you're well! 👋 

(very similar to https://github.com/Sec-ant/prettier-plugin-embed/issues/34, maybe the same issue)

[`sql-formatter`](https://github.com/sql-formatter-org/sql-formatter) crashes with `prettier-plugin-embed`, embedded SQL in JavaScript/TypeScript template string and [`prettier-plugin-sql`](https://github.com/un-ts/prettier/tree/master/packages/sql), when a cast is used:

`a.sql`

```sql
SELECT '[]'::jsonb;
```

`a.js`

```js
function up(sql) {
  await sql`SELECT '[]'::jsonb;`;
}
```

```bash
$ pnpm prettier a.sql --write
a.sql 58ms

$ pnpm prettier a.js --write
a.js
Error: Parse error: Unexpected "::jsonb;" at line 1 column 12
    at TokenizerEngine.createParseError (file:///Users/k/p/project/node_modules/sql-formatter/lib/lexer/TokenizerEngine.js:53:12)
    at TokenizerEngine.tokenize (file:///Users/k/p/project/node_modules/sql-formatter/lib/lexer/TokenizerEngine.js:35:22)
    at Tokenizer.tokenize (file:///Users/k/p/project/node_modules/sql-formatter/lib/lexer/Tokenizer.js:16:47)
    at LexerAdapter.tokenize (file:///Users/k/p/project/node_modules/sql-formatter/lib/parser/createParser.js:16:76)
    at LexerAdapter.reset (file:///Users/k/p/project/node_modules/sql-formatter/lib/parser/LexerAdapter.js:17:24)
    at Parser.feed (/Users/k/p/project/node_modules/nearley/lib/nearley.js:281:15)
    at Object.parse (file:///Users/k/p/project/node_modules/sql-formatter/lib/parser/createParser.js:26:18)
    at Formatter.parse (file:///Users/k/p/project/node_modules/sql-formatter/lib/formatter/Formatter.js:32:49)
    at Formatter.format (file:///Users/k/p/project/node_modules/sql-formatter/lib/formatter/Formatter.js:25:22)
    at formatDialect (file:///Users/k/p/project/node_modules/sql-formatter/lib/sqlFormatter.js:78:57)
a.js 40ms (unchanged)
```

Other casts that also fail:

```sql
SELECT '[]'::jsonb->0;
SELECT ARRAY['5', '6']::int[];
```

## Tildes

This also crashes similarly on the `~` (tilde) operator:

```sql
SELECT 'ABC' ~ '^[A-Z]{3}$';
```

Error:

```
Error: Parse error: Unexpected "~ '^ABC$';" at line 1 column 14
```

## Square brackets for PostgreSQL exact length arrays

Another failing pattern:

```sql
CREATE TABLE x(
        y integer[5]
  )
```

```
Error: Parse error: Unexpected "[5]
  )" at line 2 column 18
```

## `$$` delimiter

- https://github.com/Sec-ant/prettier-plugin-embed/issues/34

---

At first, from the error messages, I thought it was the lack of support for casts or tilde operators or square brackets in `sql-formatter`, but they are all supported with [`prettier-plugin-sql`](https://github.com/un-ts/prettier/tree/master/packages/sql) when used directly with `.sql` files.

My versions and config, maybe I've configured something incorrectly? 🤔

`package.json`

```json
    "prettier": "3.1.0",
    "prettier-plugin-embed": "0.2.5",
    "prettier-plugin-sql": "0.16.0",
```

`prettier.config.mjs`

```js
/** @type {import('prettier').Config} */
const prettierConfig = {
  plugins: [
    'prettier-plugin-tailwindcss',
    'prettier-plugin-embed',
    'prettier-plugin-sql',
  ],
  // Avoid excessive diffs on changes to MDX files
  proseWrap: 'never',
  singleQuote: true,
  trailingComma: 'all',
};

/** @type {import('prettier-plugin-embed').PrettierPluginEmbedOptions} */
const prettierPluginEmbedConfig = {
  embeddedSqlIdentifiers: ['sql'],
};

/** @type {import('prettier-plugin-sql').SqlBaseOptions} */
const prettierPluginSqlConfig = {
  language: 'postgresql',
  keywordCase: 'upper',
  // - Wrap all parenthesized expressions to new lines (eg. `INSERT` columns)
  // - Do not wrap foreign keys (eg. `REFERENCES table_name (id)`)
  // - Do not wrap column type expressions (eg. `VARCHAR(255)`)
  expressionWidth: 8,
};

const config = {
  ...prettierConfig,
  ...prettierPluginEmbedConfig,
  ...prettierPluginSqlConfig,
};

export default config;
```

cc @JounQin

**Comment by karlhorky** [comment]
Oh interesting, I just upgraded to `sql-formatter@14.0.0`, which offers better error messages, and it hinted that the dialect in my config above is not being passed through `prettier-plugin-sql` to `sql-formatter`:

```
This likely happens because you're using the default "sql" dialect.
If possible, please select a more specific dialect (like sqlite, postgresql, etc).
```

**Comment by karlhorky** [comment]
Patching `sql-formatter` [`lib/sqlFormatter.js` file](https://github.com/sql-formatter-org/sql-formatter/blob/7978ec3eae312c2c001bce71a04e80a0a19632ef/src/sqlFormatter.ts#L65) to hard-code the `'postgresql'` dialect / language as below seems to work

```diff
-const canonicalDialectName = dialectNameMap[cfg.language || 'sql'];
+const canonicalDialectName = dialectNameMap['postgresql'];
```

Maybe the option is being recognized / passed incorrectly through `prettier-plugin-sql` when `prettier-plugin-embed` is used?

**Comment by Sec-ant** [comment]
`sql` is a dialect name, so when it is used as an identifier, its following template is mapped to `sql`.

Check #26 and the introduction of `embeddedOverrides` in README to properly map `sql` to `postgresql`.

**Comment by JounQin** [comment]
Why not `embedLanguage` then?

**Comment by Sec-ant** [comment]
> Why not `embedLanguage` then? I'm not familiar with `prettier-plugin-embed`, just saying.

Definitely a choice if we add `embeddedSqlLanguage` or sth like that. But `prettier-plugin-sql` is currently the only plugin that supports different languages in just one plugin. So 1), I'd like to avoid adding additional options to `prettier-plugin-embed` just for a specific plugin as much as possible, it can make this plugin less maintainable. 2) `language` and `database` are 2 options already provided by `prettier-plugin-sql`, adding another option `embeddedSqlLanguage` may confuse users.

Given the rationale in #26 and this issue. I'm thinking about maybe we should disable the identifier -> dialect mapping by default and respect the `language` or `database` setting of `prettier-plugin-sql` for all identifiers. And of course we'll then need another option to enable auto mapping.

**Comment by karlhorky** [comment]
> Given the rationale in #26 and this issue. I'm thinking maybe we should disable the identifier -> dialect mapping by default and respect the `language` or `database` setting of `prettier-plugin-sql` for all identifiers

Without knowing too many details, this seems like a good approach.

It would apply `'postgresql'` for the `sql` identifier for the following configuration, which would seem to make sense to me:

```js
const config = {
  plugins: ['prettier-plugin-embed', 'prettier-plugin-sql'],
  embeddedSqlIdentifiers: ['sql'],
  language: 'postgresql',
};
```

> And of course we'll then need another option to enable auto mapping.

What about instead discarding the auto mapping altogether and requiring the user to set `language` or `database` if they want something other than the `'sql'` default?

**Comment by Sec-ant** [comment]
@karlhorky I made a PR #39. You can test that branch with the codesandebox-ci built package: https://ci.codesandbox.io/status/Sec-ant/prettier-plugin-embed/pr/39

**Comment by karlhorky** [comment]
It's working for me 🙌  for the `::jsonb->0` test case above 

`package.json`

```json
"prettier-plugin-embed": "https://pkg.csb.dev/Sec-ant/prettier-plugin-embed/commit/dc1eb180/prettier-plugin-embed"
```

**Comment by karlhorky** [comment]
Thanks for #39 and the merge + publish!

I can confirm this is working in [`prettier-plugin-embed@0.3.0`](https://github.com/Sec-ant/prettier-plugin-embed/releases/v0.3.0)
