### ISSUE TITLE
Updating v0.3.2 -> 0.4.1 breaks SQL formatting

### ISSUE THREAD

**Issue by jaydenseric** [Sec-ant/prettier-plugin-embed#58]
After updating `prettier-plugin-embed` from v0.3.2 to v0.4.1, embedded SQL formatting in `.mts` files (via `prettier-plugin-sql` v0.18.0) no longer happens, and in the VS Code output for the Prettier extension, there are no errors logged.

There is no changelog or GitHub release description to understand the changes in the v0.4 releases; what are the breaking changes? How do you migrate a project to the newer version?

**Comment by Sec-ant** [comment]
Can you provide a repro setup?

VS Code Prettier extension warnings/errors are logged by its own [logging service](https://github.com/prettier/prettier-vscode/blob/main/src/LoggingService.ts) which is not exposed to the plugins so I cannot log errors or warnings in the output panel. If you open the devtools of VS Code, the errors may appear in that window (if there're errors).

The breaking changes are the behaviors of the ruby plugin and I reduced the amount of default identifiers to only the common ones. And I've also added this [line of note](https://github.com/Sec-ant/prettier-plugin-embed#:~:text=Important%3A%20Until%20this%20notice%20is%20removed%2C%20always%20specify%20identifiers%20explicitly%20and%20do%20not%20rely%20on%20the%20built%2Din%20defaults%2C%20as%20they%20may%20be%20subject%20to%20change.) in the README file. Some new languages are added in v0.4.x compared to v0.3.2, but I don't see them as breaking changes. But maybe I broke something in the process.

This project is still in early stage, lacking tests, and I'm still trying to learn and find the appropriate process to maintain this repo. Any kind of contribution to help me organize this repo in a more maintainable way is welcome.

**Comment by jaydenseric** [comment]
The `prettier.config.mjs` contains:

```js
// @ts-check
// ignore unused exports default

// The Prettier plugin config types are temporarily avoided due to this issue:
// https://github.com/Sec-ant/prettier-plugin-embed/issues/52

// @type {import("prettier-plugin-embed").PrettierPluginEmbedOptions}
/** Prettier config for the plugin `prettier-plugin-embed`. */
const prettierConfigPluginEmbed = {
  embeddedSqlIdentifiers: ["sql", "redactedSql"],
};

// @type {import("prettier-plugin-sql").SqlBaseOptions}
/** Prettier config for the plugin `prettier-plugin-sql`. */
const prettierConfigPluginSql = {
  language: "postgresql",
};

/**
 * Prettier config.
 * @type {import("prettier").Config}
 */
const prettierConfig = {
  plugins: ["prettier-plugin-embed", "prettier-plugin-sql"],
  ...prettierConfigPluginEmbed,
  ...prettierConfigPluginSql,
};

export default prettierConfig;
```

**Comment by Sec-ant** [comment]
This is indeed a regression, sorry for the trouble. Can you test v0.4.3 to confirm whether it is fixed for your use case?

**Comment by jaydenseric** [comment]
Nice! That seems to be working again 🙌

**Comment by jaydenseric** [comment]
Hmm, something else that seems to have changed, is now the default behavior is not to format the keyword capitalization. You have to explicitly add `keywordCase: "upper"` in the SQL plugin config.

**Comment by jaydenseric** [comment]
Actually, maybe that stopped working before the v0.4 update, because now I have updated the Prettier config to enforce SQL keyword case, I'm finding Prettier formatting errors for some of the SQL committed in the last week. Maybe that default changed due to an early update of either `prettier-plugin-embed` or `prettier-plugin-sql`.

**Comment by Sec-ant** [comment]
I'm not sure but may [this](https://github.com/un-ts/prettier/issues/326) is related?
