### ISSUE TITLE
ESM support?

### ISSUE THREAD

**Issue by quantuminformation** [Sec-ant/prettier-plugin-embed#60]
I tried to use it and get

![image](https://github.com/Sec-ant/prettier-plugin-embed/assets/216566/32ffc2b6-f4a7-4f84-a29e-cb2bbb712b77)

**Comment by Sec-ant** [comment]
This is Prettier v3 plugin written as an es module. It seems you're using Prettier v2. Could you please recheck your project and if there're still errors, please provide the reproduction steps.

**Comment by quantuminformation** [comment]
thx, it works a but but didn't help much:

![image](https://github.com/Sec-ant/prettier-plugin-embed/assets/216566/ea5b2806-0bbb-41f7-a9b2-529741b33c20)

![image](https://github.com/Sec-ant/prettier-plugin-embed/assets/216566/e07dacc2-4e12-47c7-a085-6162337bd10f)

**Comment by quantuminformation** [comment]
you can try here: https://github.com/quantuminformation/vanillajs-patterns

**Comment by Sec-ant** [comment]
I'm not sure where I should look at. This plugin won't magically format your strings, it requires "identifiers" to tell it which template strings are needed to be formatted and to which language it shouble be formatted.

Would you please check the README, especially the section "An Overview of the Philosophy" to get a basic idea of how this plugin works and then label your template strings with the identifiers that can be understand by this plugin?

**Comment by Sec-ant** [comment]
This plugin doesn't support line comments like ``` //language=CSS ``` as indicators because their placement is limited to lines, not tokens.

If you need formatting support, please use block comments like ``` /* css */ ``` followed by the string template you want to format.

**Comment by Sec-ant** [comment]
@quantuminformation Do you have other questions or can we close this issue?

**Comment by quantuminformation** [comment]
im good thx
