### ISSUE TITLE
Support for object properties as identifiers

### ISSUE THREAD

**Issue by ehoogeveen-medweb** [Sec-ant/prettier-plugin-embed#64]
In our codebase we use the following syntax:
```js
const lang = "JavaScript";
const embedded = Syntax.js`const foo =  "This is embedded ${lang}!"; console.log(foo)`;
```
Unfortunately this doesn't appear to be supported by the plugin. I tried configuring it like this:
```json
{
  "plugins": ["prettier-plugin-embed"],
  "embeddedEsIdentifiers": ["Syntax.js"]
}
```
but Prettier doesn't touch the embedded JavaScript.

It does work if I use
```js
const lang = "JavaScript";
const embedded = /* js */`const foo =  "This is embedded ${lang}!"; console.log(foo)`;
```
or
```js
const lang = "JavaScript";
const embedded = js`const foo =  "This is embedded ${lang}!"; console.log(foo)`;
```
I'll consider updating our codebase to use the comment form, but obviously I'd prefer it if our current syntax would work :)

**Comment by Sec-ant** [comment]
Hey, thanks for the suggestion. This was [actually considered](https://github.com/Sec-ant/prettier-plugin-embed/blob/main/src%2Futils.ts#L163-L164) but it's not easy to design and expose an appropriate customizable option to the users.

The problem is that ``` Syntax.js`...` ``` and ``` js`...` ``` have different AST structures. And the `embedded<Language>Identifiers` only applies to the latter structure for simplicity (for end users).

For object property accessing, dot notation and bracket notation also have different structures. And there might be static analysis involved (`Syntax["j" + "s"]`) if we decide to go down that rabbit hole.

But I understand the needs so let's see if I can support some very basic forms of new structures, like a plain dot notation, just like the way you configured in your post.

**Comment by ehoogeveen-medweb** [comment]
Thanks! I figured it might be AST-related given the use of "identifier", but yeah I don't need anything other than dot notation with a fixed set of properties. The way it works in our codebase right now is that we import the `Syntax` object from a TS file, so the properties are fully typed and documented (the tag functions are stripped from the output files).

**Comment by ehoogeveen-medweb** [comment]
FWIW, in the code to strip the tag functions we do this:
1. In `TaggedTemplateExpression` with `const tag = path.node.tag`
2. Check if `tag.type == 'MemberExpression'`
3. Check if `tag.object.type == 'Identifier'` and check if `tag.object.name` is the known object name (`Syntax`)
4. Check if `tag.property.type == 'Identifier'` and check if `tag.property.name` is one of the known properties

I guess nested objects would get more complicated.

**Comment by ehoogeveen-medweb** [comment]
Yeah we only use it for syntax highlighting right now, the actual type doesn't matter other than being able to hover over it and see the documentation. Most of our code is still JavaScript.

**Comment by Sec-ant** [comment]
I see, thanks. I'm trying to get a grasp of the real world use cases that can benefit from this plugin :)

**Comment by Sec-ant** [comment]
@ehoogeveen-medweb Would you try out the [codesandbox-ci test build](https://github.com/Sec-ant/prettier-plugin-embed/pull/65#issuecomment-1894063973) in #65 to see if object properties "identifiers" will work in your project?

The config is the same as what you posted:

```json
{
  "plugins": ["prettier-plugin-embed"],
  "embeddedEsIdentifiers": ["Syntax.js"]
}
```

**Comment by Sec-ant** [comment]
> is there a way to make it format embedded code as vue-html

It is not supported currently. The parser name is [hardcoded to `html`](https://github.com/Sec-ant/prettier-plugin-embed/blob/098e82b5b8b1de1cbc9ee0aa1c0d5682653a8751/src/embedded/html/embedder.ts#L46) when you use `embeddedHtmlIdentifiers`. You'll need the [`vue` parser](https://github.com/prettier/prettier/blob/6c6a332171f590a38c369673662d1a5baf765167/src/language-html/parser-html.js#L430-L447) when dealing with vue templates. You can file a new issue if you want the support.

**Comment by Sec-ant** [comment]
Shipped in v0.4.5.

**Comment by Sec-ant** [comment]
FWIW, in v0.4.6 I added a new option `embeddedHtmlParsers` where you can set the parser to `vue` (along with other parsers `html`(default), `angular`, `lwc`). I'm not sure about their differences. So there may be strange behaviors. But at least it is supported :)

**Comment by ehoogeveen-medweb** [comment]
Oh, thank you! I'll have to experiment with it and see how well it works :)
