### ISSUE TITLE
Version 0.4.11 and 0.4.12 prevent typescript from formatting. 

### ISSUE THREAD

**Issue by robreiss** [Sec-ant/prettier-plugin-embed#78]
There seems to be a problem with 0.4.11 and 0.4.12. My typescript and tsx files are not formatting when I include prettier-plugin-embed as a plugin.

If I revert to 0.4.10 my typescript files correctly format. If I move to 0.4.11 or 0.4.12 they no longer format. I don't see any errors in the prettier logs. 

I simplified my prettier config to:
const config = {
  plugins: ["prettier-plugin-tailwindcss", "prettier-plugin-embed"],
  endOfLine: 'lf',
  singleQuote: true,
  tabWidth: 2,
  printWidth: 80,
  useTabs: false,
}

If I remove "prettier-plugin-embed" as a plugin in the config formatting works again.

**Comment by Sec-ant** [comment]
Now that's a bummer. Can you provide more information, like whether it doesn't work on all ts/tsx files or only some particular ones? Can you provide a small example? Thanks 🙏

**Comment by Sec-ant** [comment]
This should be fixed in v0.4.13, can you confirm? Thanks

**Comment by robreiss** [comment]
Works. Thanks!
